CREATE TABLE superstore (
    "Order ID" VARCHAR(50),
    "Order Date" DATE,
    "Ship Date" DATE,
    "Ship Mode" VARCHAR(50),
    "Customer ID" VARCHAR(50),
    "Customer Name" VARCHAR(100),
    "Segment" VARCHAR(50),
    "Country" VARCHAR(50),
    "City" VARCHAR(50),
    "State" VARCHAR(50),
    "Postal Code" VARCHAR(20),
    "Region" VARCHAR(50),
    "Product ID" VARCHAR(50),
    "Category" VARCHAR(50),
    "Sub-Category" VARCHAR(50),
    "Product Name" VARCHAR(100),
    "Sales" NUMERIC,
    "Quantity" INT,
    "Discount" NUMERIC,
    "Profit" NUMERIC,
    "Order Month" VARCHAR(20),
    "Order Year" INT,
    "Order Day" VARCHAR(20),
    "Profit Margin (%)" NUMERIC,
    "Shipping Time (Days)" INT
);